---
# Tasks to set/reset the root account password


- name: root password | ensure MySQL is started
  ansible.builtin.service:
    name: "{{ mysql_service }}"
    state: started
    enabled: yes
  become: yes

- name: root password | generate random password
  ansible.builtin.shell: date +%s | sha256sum | base64 | head -c 32 ; echo
  register: _mysql_random_password
  when: mysql_root_password is not defined
  changed_when: false

- name: root password | set a root user password
  ansible.builtin.command:
    argv:
      - /usr/bin/mysqladmin
      - "-u"
      - "root"
      - "password"
      - "{{ mysql_root_password|default(_mysql_random_password.stdout) }}"
  become: yes

- name: root password | set the client configuration file for root
  ansible.builtin.template:
    src: client_my.cnf.j2
    dest: "/root/.my.cnf"
    owner: "root"
    mode: 0600
  become: yes

- name: root password | set the client configuration file for admin users
  ansible.builtin.template:
    src: client_my.cnf.j2
    dest: "/home/{{ item }}/.my.cnf"
    owner: "{{ item }}"
    mode: 0600
  loop: "{{ mysql_admin_users + [devops_user|default(ansible_user)] }}"
  become: yes

- name: root password | restart MySQL
  ansible.builtin.service:
    name: "{{ mysql_service }}"
    state: restarted
  become: yes
